# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test-ui:
    executor: node/default

    resource_class: small
    working_directory: ~/project/ui
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install JUnit coverage reporter
          command: npm install --dev jest-junit
      - node/install-packages:
          cache-path: ~/project/ui/node_modules
          override-ci-command: npm install
      - run: 
          name: Run tests
          command: npm run test -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT_DIR: ./reports/junit
      - store_test_results:
          path: ./reports/junit
      - store_artifacts:
          path: ./reports/junit
workflows:
  test:
    jobs:
      - test-ui