# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    working_directory: ~/ui
    steps:
      - checkout
      - run: npm install
      - run: npm test